version: '3'

services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=5000
      - RENDER=true
    command: python index.py