name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Copy files to EC2 instance
      run: |
        scp -i private_key.pem -o StrictHostKeyChecking=no -r ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app

    - name: SSH into EC2 and deploy
      run: |
        ssh -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} 'bash -s' < ./deploy.sh
